version: "3.8"

services:
  admin:
    build: .
    container_name: admin-service
    environment:
      - URL=DEV
      - ADMIN_SERVICE=http:18.183.130.66
      - USERS_SERVICE=http:18.183.130.66
      - LOCATIONS_SERVICE=http:18.183.130.66
      - MONGO_URI=mongodb+srv://abin:znqL2fMmNbNZvLMM@cluster0.aeuw9.mongodb.net/travel-buddy?retryWrites=true&w=majority
      - JWT_SECRET=mysecret
      - NEXT_PUBLIC_OPENROUTESERVICE_API_KEY=5b3ce3597851110001cf6248446cfecdccf8487da5902daacee5eef8
      - NEXT_PUBLIC_OPENRWEATHERMAP_API_URI=https://api.openweathermap.org/data/2.5/weather
      - NEXT_PUBLIC_OPENRWEATHERMAP_API_KEY=853f59413a67058c98405c1e556eef84
      - GOOGLE_MAPS_API_KEY=AIzaSyAVUAshUqM-uF20_ytuYl0Ay3BdJLB5kGQ
    command: npm run st:admin
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http:18.183.130.66/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  users:
    build: .
    container_name: user-service
    environment:
      - URL=DEV
      - ADMIN_SERVICE=http:18.183.130.66
      - USERS_SERVICE=http:18.183.130.66
      - LOCATIONS_SERVICE=http:18.183.130.66
      - MONGO_URI=mongodb+srv://abin:znqL2fMmNbNZvLMM@cluster0.aeuw9.mongodb.net/travel-buddy?retryWrites=true&w=majority
      - JWT_SECRET=mysecret
      - NEXT_PUBLIC_OPENROUTESERVICE_API_KEY=5b3ce3597851110001cf6248446cfecdccf8487da5902daacee5eef8
      - NEXT_PUBLIC_OPENRWEATHERMAP_API_URI=https://api.openweathermap.org/data/2.5/weather
      - NEXT_PUBLIC_OPENRWEATHERMAP_API_KEY=853f59413a67058c98405c1e556eef84
      - GOOGLE_MAPS_API_KEY=AIzaSyAVUAshUqM-uF20_ytuYl0Ay3BdJLB5kGQ
    command: npm run st:user
    ports:
      - "5002:5002"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http:18.183.130.66/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  locations:
    build: .
    container_name: location-service
    environment:
      - URL=DEV
      - ADMIN_SERVICE=http:18.183.130.66
      - USERS_SERVICE=http:18.183.130.66
      - LOCATIONS_SERVICE=http:18.183.130.66
      - MONGO_URI=mongodb+srv://abin:znqL2fMmNbNZvLMM@cluster0.aeuw9.mongodb.net/travel-buddy?retryWrites=true&w=majority
      - JWT_SECRET=mysecret
      - NEXT_PUBLIC_OPENROUTESERVICE_API_KEY=5b3ce3597851110001cf6248446cfecdccf8487da5902daacee5eef8
      - NEXT_PUBLIC_OPENRWEATHERMAP_API_URI=https://api.openweathermap.org/data/2.5/weather
      - NEXT_PUBLIC_OPENRWEATHERMAP_API_KEY=853f59413a67058c98405c1e556eef84
      - GOOGLE_MAPS_API_KEY=AIzaSyAVUAshUqM-uF20_ytuYl0Ay3BdJLB5kGQ
    command: npm run st:location
    ports:
      - "5003:5003"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http:18.183.130.66/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-gateway:
    build: .
    container_name: api-gateway
    environment:
      - URL=DEV
      - ADMIN_SERVICE=http:18.183.130.66
      - USERS_SERVICE=http:18.183.130.66
      - LOCATIONS_SERVICE=http:18.183.130.66
      - MONGO_URI=mongodb+srv://abin:znqL2fMmNbNZvLMM@cluster0.aeuw9.mongodb.net/travel-buddy?retryWrites=true&w=majority
      - JWT_SECRET=mysecret
      - NEXT_PUBLIC_OPENROUTESERVICE_API_KEY=5b3ce3597851110001cf6248446cfecdccf8487da5902daacee5eef8
      - NEXT_PUBLIC_OPENRWEATHERMAP_API_URI=https://api.openweathermap.org/data/2.5/weather
      - NEXT_PUBLIC_OPENRWEATHERMAP_API_KEY=853f59413a67058c98405c1e556eef84
      - GOOGLE_MAPS_API_KEY=AIzaSyAVUAshUqM-uF20_ytuYl0Ay3BdJLB5kGQ
    command: npm run st:server
    ports:
      - "5000:5000"
    depends_on:
      - admin
      - users
      - locations
    healthcheck:
      test: ["CMD", "curl", "-f", "http://l18.183.130.66/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/default.conf:ro
    depends_on:
      - api-gateway

volumes:
  mongo-data:
