
services:
  admin:
    build: .
    container_name: admin-service
    environment:
      - URL=PROD
    command: npm run st:admin
    ports:
      - "5001:5001"
    depends_on:
      - mongo

  users:
    build: .
    container_name: user-service
    environment:
      - URL=PROD
    command: npm run st:user
    ports:
      - "5002:5002"
    depends_on:
      - mongo

  locations:
    build: .
    container_name: location-service
    environment:
      - URL=PROD
    command: npm run st:location
    ports:
      - "5003:5003"
    depends_on:
      - mongo

  api-gateway:
    build: .
    container_name: api-gateway
    environment:
      - URL=PROD
    command: npm run st:server
    ports:
      - "5000:5000"
    depends_on:
      - admin
      - users
      - locations

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api-gateway

volumes:
  mongo-data:
